### ISSUE TITLE
Could not initialize class teammt.anvilgui.AnvilGUI

### ISSUE THREAD

**Issue by Slyvver** [Gargant0373/ItemBuilderPlus#1]
The UI loads, but when I click on ANYTHING, I get the above error...

**Comment by Gargant0373** [comment]
Hello! What version are you using and what plugins do you have installed?
Please also provide the full stack trace of the error.

**Comment by Slyvver** [comment]
What version of your mod? Here are the plugins currently used:
ItemBuilderPlus-0.0.1-SNAPSHOT.jar
LuckPerms-Bukkit-5.3.86.jar
SafeNBT.jar

I believe that this is the part of the stack trace that you want:
[09:30:36] [Server thread/INFO]: [ItemBuilderPlus] Enabling ItemBuilderPlus v1.0
[09:30:36] [Server thread/INFO]: LOGGER [ItemBuilderPlus] | WARN: You no placeholder container found! (PAPI, MVdWPAPI). The internal one will be used!
[09:30:36] [Server thread/INFO]: LOGGER [ItemBuilderPlus] | INFO: Server version is most likely 1.8.0 (0, v1_8_R1)
[09:30:36] [Server thread/INFO]: [SafeNBT] Enabling SafeNBT v2.1
[09:30:36] [Server thread/INFO]: [SafeNBT] Successfully enabled SafeNBT by jojodmo!
...
[10:19:22] [Server thread/ERROR]: Could not pass event InventoryClickEvent to ItemBuilderPlus v1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2439) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1114) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3398-Spigot-f4ff00f-f3828bb]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at teammt.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[?:?]
	at gargant.itembuilder.containers.ItemBuildContainer.onTopClick(ItemBuildContainer.java:89) ~[?:?]
	at masecla.ItemBuilderPlus.mlib.apis.ContainerAPI$1.onClick(ContainerAPI.java:74) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 20 more
Caused by: java.lang.RuntimeException: Your server version isn't supported in AnvilGUI!
	at teammt.anvilgui.version.VersionMatcher.lambda$match$1(VersionMatcher.java:52) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at teammt.anvilgui.version.VersionMatcher.match(VersionMatcher.java:52) ~[?:?]
	at teammt.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[?:?]
	at teammt.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[?:?]
	at gargant.itembuilder.containers.ItemBuildContainer.onTopClick(ItemBuildContainer.java:89) ~[?:?]
	at masecla.ItemBuilderPlus.mlib.apis.ContainerAPI$1.onClick(ContainerAPI.java:74) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 20 more
[10:19:25] [Server thread/ERROR]: Could not pass event InventoryClickEvent to ItemBuilderPlus v1.0
-----------------------------
All that being said, it looks as if the problem is with "AnvilGUI". WHERE should I be downloading it? Or is it included with your mod?? It should be pretty clear that I'm new to all of this, and have been stumbling around.

**Comment by Gargant0373** [comment]
It looks like the API I use for AnvilGUIs doesn't support your MC version. What version is your server running?

**Comment by Slyvver** [comment]
1.18.1?
